# Generated by Django 4.2.5 on 2024-04-16 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegateentertainment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
